name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main   # change to master if that's your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BOOKWARE_SITE }}
          projectId: bookware-site-b04b7
          channelId: live
          entryPoint: ./mysite
